### ISSUE TITLE
Changes to website content

### ISSUE THREAD

**Issue by salman-5** [salman-5/react-app#42]
Check the font sizes in mobile and desktop view

Nav Bar - No need for Contact and Get Started (Get A Quote), change order of menus, products not link
Our Products: bullet point each configs
Footer: update logo of social media
Make Learn more button make it more highlight
Generate new content for About Us make it attractive
Gallery upload new images (Change color style ?)

Make different configurations more presentable - possibility and performance data highlight on active
Bifold Page
Fill form to send email

**Comment by Ajnas-A** [comment]
const cards = [
    {
      imageUrl: "./asset/hi-bifold-2.jpg",
      title: "Bifold Door Sytems",
      descriptions:
        "Experience Limitless Potential with Bifold Door Systems! Meet the BF 3700 TB for climate-controlled serenity. \n Discover the BF 80 PLUS, a design revolution with abundant natural light. \n Unleash the Monumental Bi-Fold's epic proportions and hurricane-proof might. These systems redefine spaces and elevate your expectations. Explore the future of architecture today!",
    },
    {
      imageUrl: "./asset/cor-vision-2.jpg",
      title: "Sliding Door Systems",
      descriptions:
        "Unleash Your Architectural Vision with CORTIZO's Cutting-Edge Sliding Doors! Revitalize your spaces with excitement! From the ultra-modern 4600 HI LIFT AND SLIDE to the expansive 4700 SLIDING system, and the minimalist elegance of COR VISION, to the grandeur of COR VISION PLUS - CORTIZO's innovations are redefining what's possible in design. Dive in now!",
    },
    {
      imageUrl: "./asset/mill-panel-2.jpg",
      title: "Millenium Doors",
      descriptions:
        "Experience the Future of Entrances with MILLENNIUM PLUS! MILLENNIUM PLUS 70 and 80 bring high insulation and sleek lines to your spaces. Add style with MILLENNIUM PLUS PANEL DOOR, featuring integrated panels and LED handles. Get ready for innovation with MILLENNIUM PLUS PIVOT DOOR, offering top performance and smart features like embedded LED handles and smart-home integration. Welcome to tomorrow's entrances, today!",
    },
    {
      imageUrl: "./asset/mill-panel-2.jpg",
      title: "Millenium Doors",
      descriptions:
        "Experience the Future of Entrances with MILLENNIUM PLUS! MILLENNIUM PLUS 70 and 80 bring high insulation and sleek lines to your spaces. Add style with MILLENNIUM PLUS PANEL DOOR, featuring integrated panels and LED handles. Get ready for innovation with MILLENNIUM PLUS PIVOT DOOR, offering top performance and smart features like embedded LED handles and smart-home integration. Welcome to tomorrow's entrances, today!",
    },
    {
      imageUrl: "./asset/mill-panel-2.jpg",
      title: "Millenium Doors",
      descriptions:
        "Experience the Future of Entrances with MILLENNIUM PLUS! MILLENNIUM PLUS 70 and 80 bring high insulation and sleek lines to your spaces. Add style with MILLENNIUM PLUS PANEL DOOR, featuring integrated panels and LED handles. Get ready for innovation with MILLENNIUM PLUS PIVOT DOOR, offering top performance and smart features like embedded LED handles and smart-home integration. Welcome to tomorrow's entrances, today!",
    },
    {
      imageUrl: "./asset/mill-panel-2.jpg",
      title: "Millenium Doors",
      descriptions:
        "Experience the Future of Entrances with MILLENNIUM PLUS! MILLENNIUM PLUS 70 and 80 bring high insulation and sleek lines to your spaces. Add style with MILLENNIUM PLUS PANEL DOOR, featuring integrated panels and LED handles. Get ready for innovation with MILLENNIUM PLUS PIVOT DOOR, offering top performance and smart features like embedded LED handles and smart-home integration. Welcome to tomorrow's entrances, today!",
    },
    {
      imageUrl: "./asset/mill-panel-2.jpg",
      title: "Millenium Doors",
      descriptions:
        "Experience the Future of Entrances with MILLENNIUM PLUS! MILLENNIUM PLUS 70 and 80 bring high insulation and sleek lines to your spaces. Add style with MILLENNIUM PLUS PANEL DOOR, featuring integrated panels and LED handles. Get ready for innovation with MILLENNIUM PLUS PIVOT DOOR, offering top performance and smart features like embedded LED handles and smart-home integration. Welcome to tomorrow's entrances, today!",
    },
  ];

**Comment by Ajnas-A** [comment]
{cards.map((card, index) => (
          <div className="w-[450px] flex space-x-5 h-full">
            <CarousalCard
              title={index}
              desc={card.descriptions}
              imageUrl={card.imageUrl}
            />
          </div>
        ))}

**Comment by salman-5** [comment]
All good
